# Generated by Django 6.0.1 on 2026-04-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_image_url',
            field=models.URLField(blank=True, default='', help_text='Optional icon image URL (e.g. a small PNG/SVG). Recommended size: ~64x64.'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_label',
            field=models.CharField(blank=True, default='', help_text="Optional short label shown when no icon image is provided (e.g. 'Checkup').", max_length=80),
        ),
    ]
