# Generated by Django 6.0.1 on 2026-04-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_service_icon_service_icon_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_image_url',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon_label',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload a small icon image (PNG preferred). Recommended size: ~64x64.', null=True, upload_to='service-icons/'),
        ),
    ]
