# Generated by Django 6.0.1 on 2026-04-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_service_icon_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_body',
            field=models.TextField(default='Welcome to TuYou Dental Care, where brightening your smile brightens our day.\n\nWe offer a comprehensive range of treatments, from routine cleanings and preventative care to advanced cosmetic, prosthetic and restorative procedures. We believe in personalized care tailored to meet the unique needs of each patient, ensuring a comfortable and stress-free experience.\n\nOur state-of-the-art facility is equipped with the latest technology to deliver the highest standard of dental care. Trust TuYou Dental Care to help you achieve and maintain a healthy, beautiful smile.\n\n“We Cure With full cure”'),
        ),
    ]
