# Generated by Django 6.0.1 on 2026-04-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_sitesettings_about_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='approved',
            field=models.BooleanField(default=True, help_text='If unchecked, this testimonial will not be shown on the public website.'),
        ),
    ]
