# Generated by Django 6.0.1 on 2026-04-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_testimonial_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a profile photo (square image recommended).', null=True, upload_to='team/'),
        ),
    ]
