# Generated by Django 6.0.1 on 2026-04-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_teammember_photo_url_teammember_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
