# Generated by Django 6.0.1 on 2026-04-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_galleryimage_image_url_galleryimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='about_image_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_image_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
